# 
# This workflow will clean the existing contents and then execute a maven command
#
name: Clean and maven command

on:
  workflow_call:
    inputs:
        maven-command:
          required: true
          type: string    
    secrets:
      SONAR_TOKEN:
        required: true        

jobs:
    
  clean_and_build:
    uses: ./.github/workflows/_maven.yml
    with:
      maven-command: clean install
      maven-command-extra: ${{ inputs.maven-command }}
      os: ubuntu-latest
      java-version: 8
    secrets: inherit    
