# 
# This workflow will build and test a Java project with Maven.
#
# It is only triggered on master branch.
#
# It also:
#   - updates the corresponding project on SonarCloud
#  -  uploads the built artifacts to GitHub Packages
#
# The Maven and SonarCloud working directories are cached for future reuse, as downloading all packages from scratch takes significant time.
#
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#

name: Java CI with Maven for Master

on:
  push:
    branches: [ master ]

jobs:
  deploy_and_javadoc:
    uses: ./.github/workflows/_clean_maven.yml
    with:
      maven-command: javadoc:jar source:jar deploy
    secrets: inherit
      
  sonarcloud:
    uses: ./.github/workflows/_sonarcloud.yml
    secrets: inherit
